#!/usr/bin/env node

/**
 * @file
 * Binding Component starter automatically generated by
 * the Social Communication Platform.
 */

const bc = require('./amqp-endpoint');
const fb = require('./routes/messenger');

bc.listen();
fb.listen();
